# Generated by Django 5.0.3 on 2024-04-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workhour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktime",
            name="actual_work_time",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="worktime",
            name="month",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="worktime",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
